FROM alpine:3.7

LABEL maintainer="userundefined"

RUN apk add --update \
    python \
    py-pip \
  && pip install flask -U \
  && rm -rf /var/cache/apk/* \
  && adduser -D app \
  && mkdir /foo  \
  && chown -R app:app /foo

RUN pip install --upgrade pip

# Copy the current directory contents into the container at /app
COPY . /app

WORKDIR /app

# RUN pip install -r ./requirements.txt

RUN pip install Flask==1.0.2
# RUN pip install tensorflow==1.8.0
RUN pip install https://github.com/better/alpine-tensorflow/releases/download/alpine3.7-tensorflow1.7.0/tensorflow-1.7.0-cp36-cp36m-linux_x86_64.whl

# Expose port 8000
EXPOSE 8000

CMD ["python", "app.py"]
